Import of version 22.11. The mDNSresponder package has been removed as the version number we used has been reused and is now incompatible. The next version will add mDNSresponder back.

diff --git a/linux/tools/testing/selftests/vm/Makefile b/linux/tools/testing/selftests/vm/Makefile
--- a/linux/tools/testing/selftests/vm/Makefile
+++ b/linux/tools/testing/selftests/vm/Makefile
@@ -1,35 +1,68 @@
 # SPDX-License-Identifier: GPL-2.0
 # Makefile for vm selftests
-uname_M := $(shell uname -m 2>/dev/null || echo not)
-MACHINE ?= $(shell echo $(uname_M) | sed -e 's/aarch64.*/arm64/')
 
-CFLAGS = -Wall -I ../../../../usr/include $(EXTRA_CFLAGS)
-LDLIBS = -lrt
+LOCAL_HDRS += $(selfdir)/vm/local_config.h $(top_srcdir)/mm/gup_test.h
+
+include local_config.mk
+
+uname_M := $(shell uname -m 2>/dev/null || echo not)
+MACHINE ?= $(shell echo $(uname_M) | sed -e 's/aarch64.*/arm64/' -e 's/ppc64.*/ppc64/')
+
+# Without this, failed build products remain, with up-to-date timestamps,
+# thus tricking Make (and you!) into believing that All Is Well, in subsequent
+# make invocations:
+.DELETE_ON_ERROR:
+
+# Avoid accidental wrong builds, due to built-in rules working just a little
+# bit too well--but not quite as well as required for our situation here.
+#
+# In other words, "make userfaultfd" is supposed to fail to build at all,
+# because this Makefile only supports either "make" (all), or "make /full/path".
+# However,  the built-in rules, if not suppressed, will pick up CFLAGS and the
+# initial LDLIBS (but not the target-specific LDLIBS, because those are only
+# set for the full path target!). This causes it to get pretty far into building
+# things despite using incorrect values such as an *occasionally* incomplete
+# LDLIBS.
+MAKEFLAGS += --no-builtin-rules
+
+CFLAGS = -Wall -I ../../../../usr/include $(EXTRA_CFLAGS) $(KHDR_INCLUDES)
+LDLIBS = -lrt -lpthread
 TEST_GEN_FILES = compaction_test
-TEST_GEN_FILES += gup_benchmark
+TEST_GEN_FILES += gup_test
 TEST_GEN_FILES += hmm-tests
+TEST_GEN_FILES += hugetlb-madvise
 TEST_GEN_FILES += hugepage-mmap
+TEST_GEN_FILES += hugepage-mremap
 TEST_GEN_FILES += hugepage-shm
-TEST_GEN_FILES += map_hugetlb
+TEST_GEN_FILES += hugepage-vmemmap
+TEST_GEN_FILES += khugepaged
+TEST_GEN_PROGS = madv_populate
 TEST_GEN_FILES += map_fixed_noreplace
+TEST_GEN_FILES += map_hugetlb
 TEST_GEN_FILES += map_populate
+TEST_GEN_FILES += memfd_secret
+TEST_GEN_FILES += migration
 TEST_GEN_FILES += mlock-random-test
 TEST_GEN_FILES += mlock2-tests
+TEST_GEN_FILES += mrelease_test
 TEST_GEN_FILES += mremap_dontunmap
+TEST_GEN_FILES += mremap_test
 TEST_GEN_FILES += on-fault-limit
 TEST_GEN_FILES += thuge-gen
 TEST_GEN_FILES += transhuge-stress
 TEST_GEN_FILES += userfaultfd
-TEST_GEN_FILES += khugepaged
+TEST_GEN_PROGS += soft-dirty
+TEST_GEN_PROGS += split_huge_page_test
+TEST_GEN_FILES += ksm_tests
 
-ifeq ($(ARCH),x86_64)
-CAN_BUILD_I386 := $(shell ./../x86/check_cc.sh $(CC) ../x86/trivial_32bit_program.c -m32)
-CAN_BUILD_X86_64 := $(shell ./../x86/check_cc.sh $(CC) ../x86/trivial_64bit_program.c)
-CAN_BUILD_WITH_NOPIE := $(shell ./../x86/check_cc.sh $(CC) ../x86/trivial_program.c -no-pie)
+ifeq ($(MACHINE),x86_64)
+CAN_BUILD_I386 := $(shell ./../x86/check_cc.sh "$(CC)" ../x86/trivial_32bit_program.c -m32)
+CAN_BUILD_X86_64 := $(shell ./../x86/check_cc.sh "$(CC)" ../x86/trivial_64bit_program.c)
+CAN_BUILD_WITH_NOPIE := $(shell ./../x86/check_cc.sh "$(CC)" ../x86/trivial_program.c -no-pie)
 
-TARGETS := protection_keys
-BINARIES_32 := $(TARGETS:%=%_32)
-BINARIES_64 := $(TARGETS:%=%_64)
+VMTARGETS := protection_keys
+BINARIES_32 := $(VMTARGETS:%=%_32)
+BINARIES_64 := $(VMTARGETS:%=%_64)
 
 ifeq ($(CAN_BUILD_WITH_NOPIE),1)
 CFLAGS += -no-pie
@@ -43,25 +76,32 @@ ifeq ($(CAN_BUILD_X86_64),1)
 TEST_GEN_FILES += $(BINARIES_64)
 endif
 else
+
+ifneq (,$(findstring $(MACHINE),ppc64))
 TEST_GEN_FILES += protection_keys
 endif
 
-ifneq (,$(filter $(MACHINE),arm64 ia64 mips64 parisc64 ppc64 ppc64le riscv64 s390x sh64 sparc64 x86_64))
+endif
+
+ifneq (,$(filter $(MACHINE),arm64 ia64 mips64 parisc64 ppc64 riscv64 s390x sh64 sparc64 x86_64))
 TEST_GEN_FILES += va_128TBswitch
 TEST_GEN_FILES += virtual_address_range
 TEST_GEN_FILES += write_to_hugetlbfs
 endif
 
-TEST_PROGS := run_vmtests
+TEST_PROGS := run_vmtests.sh
 
 TEST_FILES := test_vmalloc.sh
+TEST_FILES += test_hmm.sh
 
 KSFT_KHDR_INSTALL := 1
 include ../lib.mk
 
-$(OUTPUT)/hmm-tests: LDLIBS += -lhugetlbfs -lpthread
+$(OUTPUT)/madv_populate: vm_util.c
+$(OUTPUT)/soft-dirty: vm_util.c
+$(OUTPUT)/split_huge_page_test: vm_util.c
 
-ifeq ($(ARCH),x86_64)
+ifeq ($(MACHINE),x86_64)
 BINARIES_32 := $(patsubst %,$(OUTPUT)/%,$(BINARIES_32))
 BINARIES_64 := $(patsubst %,$(OUTPUT)/%,$(BINARIES_64))
 
@@ -76,19 +116,19 @@ $(1) $(1)_64: $(OUTPUT)/$(1)_64
 endef
 
 ifeq ($(CAN_BUILD_I386),1)
-$(BINARIES_32): CFLAGS += -m32
+$(BINARIES_32): CFLAGS += -m32 -mxsave
 $(BINARIES_32): LDLIBS += -lrt -ldl -lm
-$(BINARIES_32): %_32: %.c
+$(BINARIES_32): $(OUTPUT)/%_32: %.c
 	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(notdir $^) $(LDLIBS) -o $@
-$(foreach t,$(TARGETS),$(eval $(call gen-target-rule-32,$(t))))
+$(foreach t,$(VMTARGETS),$(eval $(call gen-target-rule-32,$(t))))
 endif
 
 ifeq ($(CAN_BUILD_X86_64),1)
-$(BINARIES_64): CFLAGS += -m64
+$(BINARIES_64): CFLAGS += -m64 -mxsave
 $(BINARIES_64): LDLIBS += -lrt -ldl
-$(BINARIES_64): %_64: %.c
+$(BINARIES_64): $(OUTPUT)/%_64: %.c
 	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(notdir $^) $(LDLIBS) -o $@
-$(foreach t,$(TARGETS),$(eval $(call gen-target-rule-64,$(t))))
+$(foreach t,$(VMTARGETS),$(eval $(call gen-target-rule-64,$(t))))
 endif
 
 # x86_64 users should be encouraged to install 32-bit libraries
@@ -110,6 +150,25 @@ warn_32bit_failure:
 endif
 endif
 
-$(OUTPUT)/userfaultfd: LDLIBS += -lpthread
+$(OUTPUT)/mlock-random-test $(OUTPUT)/memfd_secret: LDLIBS += -lcap
 
-$(OUTPUT)/mlock-random-test: LDLIBS += -lcap
+# HMM_EXTRA_LIBS may get set in local_config.mk, or it may be left empty.
+$(OUTPUT)/hmm-tests: LDLIBS += $(HMM_EXTRA_LIBS)
+
+$(OUTPUT)/ksm_tests: LDLIBS += -lnuma
+
+$(OUTPUT)/migration: LDLIBS += -lnuma
+
+local_config.mk local_config.h: check_config.sh
+	/bin/sh ./check_config.sh $(CC)
+
+EXTRA_CLEAN += local_config.mk local_config.h
+
+ifeq ($(HMM_EXTRA_LIBS),)
+all: warn_missing_hugelibs
+
+warn_missing_hugelibs:
+	@echo ; \
+	echo "Warning: missing libhugetlbfs support. Some HMM tests will be skipped." ; \
+	echo
+endif
diff --git a/vendors/Digi/AnywhereUSB8/digi_update_firmware b/vendors/Digi/AnywhereUSB8/digi_update_firmware
--- a/vendors/Digi/AnywhereUSB8/digi_update_firmware
+++ b/vendors/Digi/AnywhereUSB8/digi_update_firmware
@@ -310,7 +310,18 @@ fi
 	exit 1
 fi
 # Program rootfs and kernel
-if /bin/tar xvzf "$updatefile" rootfs rootfs.sig rootfs.size kernel kernel.sig; then
+if /bin/tar tvzf "$updatefile" | /bin/grep -qs ' rootfs$'; then
+	echo 'rootfs
+rootfs.sig
+rootfs.size
+kernel
+kernel.sig' >_tar.list
+	/bin/tar xvzf "$updatefile" -T _tar.list || {
+		printf "![ERROR] Unable to extract firmware from update!" >&6
+		/bin/rm _tar.list
+		exit 1
+	}
+	/bin/rm _tar.list
 	[ -n "${avail_marked}" ] || invalidate_nextboot "$next_boot"
 	avail_marked="y"
 	echo "30% Performing firmware update on system $next_boot" >&5
diff --git a/vendors/Digi/TX54-Single-Cellular/rc b/vendors/Digi/TX54-Single-Cellular/rc
--- a/vendors/Digi/TX54-Single-Cellular/rc
+++ b/vendors/Digi/TX54-Single-Cellular/rc
@@ -5,14 +5,17 @@ mount -t proc proc /proc
 mount -t sysfs sys /sys
 mkdir -m 755 /dev/pts
 mount -t devpts devpts /dev/pts
-mount -t tmpfs -o size=40M tmpfs /tmp
+mount -t tmpfs -o size=70M tmpfs /tmp
 mount -t tmpfs -o size=32M tmpfs /var
 mkdir -m 1777 /var/tmp
-mkdir -m 755 /var/log
 mkdir -m 755 /var/run
 mkdir -m 1777 /var/lock
 mkdir -m 755 /var/empty
 mkdir -m 755 /var/mnt
+
+# Setup the filesystem to host the /var/log.
+. /lib/varlog_setup.sh
+setup_varlogfs 16
 
 echo "Starting watchdog..."
 watchdog /dev/watchdog
@@ -59,7 +62,20 @@ if [ "$factory" ] ; then
 	exit 0
 fi
 
-ubiattach -p /dev/flash/userfs -d 1
+ubiattach -p /dev/flash/userfs -d 1 || {
+	echo "Failed to attach UserFS partition, re-creating it..."
+	ubiformat -q -y /dev/flash/userfs &&
+		ubiattach -p /dev/flash/userfs -d 1 ||
+		echo "Failed to create UserFS partition"
+}
+
+# Check if UserFS volume is there
+ubinfo -d 1 -N UserFS &>/dev/null || {
+	echo "UserFS volume doesn't exist, creating it..."
+	ubimkvol /dev/ubi1 -N UserFS -m ||
+		echo "Failed to create UserFS volume"
+}
+
 echo "Mounting opt filesystem...."
 if ! mount -t ubifs ubi1:UserFS /opt
 then
@@ -89,7 +105,7 @@ fi
 
 if [ -f /etc/config/.init ]; then
 	echo "Factory defaulting config ..."
-	filter="($|/ssh_host_rsa_key|/ssh_host_dsa_key|/ssh_host_key|/id_rsa|/id_dsa|/identity|/accns.pem|/accns.crt|/unique.crt|/.nocrypt|/.init2|/random-seed)"
+	filter="($|/certs$|/certs/|/ssh_host_rsa_key|/ssh_host_dsa_key|/ssh_host_key|/id_rsa|/id_dsa|/identity|/accns.pem|/accns.crt|/unique.crt|/.nocrypt|/.init2|/random-seed)"
 	[ -f /etc/config/.init2 ] && filter='($|/random-seed)'
 	touch /etc/config/.init2
 	find /etc/config -name '*' |
@@ -119,6 +135,9 @@ fi
 modprobe ath10k_pci
 
 random_seed restore
+
+# Clear any temporary power off delay
+/bin/set_temp_pwr_off_delay 0
 
 # init processing
 [ -x /etc/rcS ] && /etc/rcS
diff --git a/vendors/Digi/TX64/mkffs b/vendors/Digi/TX64/mkffs
--- a/vendors/Digi/TX64/mkffs
+++ b/vendors/Digi/TX64/mkffs
@@ -52,21 +52,21 @@ format_env() {
 
 
 if ! mount 2>&1 | grep -q tmp; then
-        echo "Mounting filesystems..."
-        mount -t proc proc /proc
-        mount -t sysfs sys /sys
-        mkdir -m 755 /dev/pts
-        mount -t devpts devpts /dev/pts
-        mount -t tmpfs -o size=256M tmpfs /tmp
-        mount -t tmpfs -o size=256M tmpfs /var
-        mkdir -m 755 /dev/hugepages
-        mount -t hugetlbfs none /dev/hugepages
-        mkdir -m 1777 /var/tmp
-        mkdir -m 755 /var/log
-        mkdir -m 755 /var/run
-        mkdir -m 1777 /var/lock
-        mkdir -m 755 /var/empty
-        mkdir -m 755 /var/mnt
+	echo "Mounting filesystems..."
+	mount -t proc proc /proc
+	mount -t sysfs sys /sys
+	mkdir -m 755 /dev/pts
+	mount -t devpts devpts /dev/pts
+	mount -t tmpfs -o size=256M tmpfs /tmp
+	mount -t tmpfs -o size=256M tmpfs /var
+	mkdir -m 755 /dev/hugepages
+	mount -t hugetlbfs none /dev/hugepages
+	mkdir -m 1777 /var/tmp
+	mkdir -m 755 /var/log
+	mkdir -m 755 /var/run
+	mkdir -m 1777 /var/lock
+	mkdir -m 755 /var/empty
+	mkdir -m 755 /var/mnt
 fi
 
 # Default drive to setup and boot from
@@ -76,8 +76,8 @@ RAWIMAGE=/dev/sdb
 # Check if this device is mounted
 if mount | grep -q $DRIVE
 then
-        echo "ERROR: drive $DRIVE is active (mounted)"
-        exit 1
+	echo "ERROR: drive $DRIVE is active (mounted)"
+	exit 1
 fi
 
 echo "Making the GPT partitions..."
diff --git a/vendors/Digi/VirtualDAL-PR/mkffs b/vendors/Digi/VirtualDAL-PR/mkffs
--- a/vendors/Digi/VirtualDAL-PR/mkffs
+++ b/vendors/Digi/VirtualDAL-PR/mkffs
@@ -7,21 +7,21 @@
 #
 
 if ! mount 2>&1 | grep -q tmp; then
-        echo "Mounting filesystems..."
-        mount -t proc proc /proc
-        mount -t sysfs sys /sys
-        mkdir -m 755 /dev/pts
-        mount -t devpts devpts /dev/pts
-        mount -t tmpfs -o size=256M tmpfs /tmp
-        mount -t tmpfs -o size=256M tmpfs /var
-        mkdir -m 755 /dev/hugepages
-        mount -t hugetlbfs none /dev/hugepages
-        mkdir -m 1777 /var/tmp
-        mkdir -m 755 /var/log
-        mkdir -m 755 /var/run
-        mkdir -m 1777 /var/lock
-        mkdir -m 755 /var/empty
-        mkdir -m 755 /var/mnt
+	echo "Mounting filesystems..."
+	mount -t proc proc /proc
+	mount -t sysfs sys /sys
+	mkdir -m 755 /dev/pts
+	mount -t devpts devpts /dev/pts
+	mount -t tmpfs -o size=256M tmpfs /tmp
+	mount -t tmpfs -o size=256M tmpfs /var
+	mkdir -m 755 /dev/hugepages
+	mount -t hugetlbfs none /dev/hugepages
+	mkdir -m 1777 /var/tmp
+	mkdir -m 755 /var/log
+	mkdir -m 755 /var/run
+	mkdir -m 1777 /var/lock
+	mkdir -m 755 /var/empty
+	mkdir -m 755 /var/mnt
 fi
 
 # Default drive to setup and boot from
@@ -34,13 +34,13 @@ IMAGESIZE=${1:-4096}
 # Check if this device is mounted
 if mount | grep -q $DRIVE
 then
-        echo "ERROR: drive $DRIVE is active (mounted)"
-        exit 1
+	echo "ERROR: drive $DRIVE is active (mounted)"
+	exit 1
 fi
 
 # delete old partitions
 for p in 1 2 3 4 5; do
-        parted --script -- $DRIVE rm $p > /dev/null 2>&1
+	parted --script -- $DRIVE rm $p > /dev/null 2>&1
 done
 
 # partition alignement helper: new_part <size|0>
@@ -48,13 +48,13 @@ done
 
 new_part()
 {
-    last=$(parted --script -- ${DRIVE} unit s print | awk '/^ *[0-9]/ { gsub("s","",$3); print $3 }' | tail -1)
-    free=$((${last:-0}+1))
-    if [ "$1" = 0 ]; then
-        echo "${free}s -0"
-    else
-        echo "${free}s $((free + (($1 * 1024 * 1024) / 512) - 1))s"
-    fi
+	last=$(parted --script -- ${DRIVE} unit s print | awk '/^ *[0-9]/ { gsub("s","",$3); print $3 }' | tail -1)
+	free=$((${last:-0}+1))
+	if [ "$1" = 0 ]; then
+		echo "${free}s -0"
+	else
+		echo "${free}s $((free + (($1 * 1024 * 1024) / 512) - 1))s"
+	fi
 }
 
 echo "Making the GPT partitions..."
