Updated to version 20.5

diff --git a/linux/tools/testing/selftests/vm/run_vmtests b/linux/tools/testing/selftests/vm/run_vmtests
--- a/linux/tools/testing/selftests/vm/run_vmtests
+++ b/linux/tools/testing/selftests/vm/run_vmtests
@@ -58,6 +58,14 @@ else
 	exit 1
 fi
 
+#filter 64bit architectures
+ARCH64STR="arm64 ia64 mips64 parisc64 ppc64 riscv64 s390x sh64 sparc64 x86_64"
+if [ -z $ARCH ]; then
+  ARCH=`uname -m 2>/dev/null | sed -e 's/aarch64.*/arm64/'`
+fi
+VADDR64=0
+echo "$ARCH64STR" | grep $ARCH && VADDR64=1
+
 mkdir $mnt
 mount -t hugetlbfs none $mnt
 
@@ -103,6 +111,17 @@ fi
 echo "NOTE: The above hugetlb tests provide minimal coverage.  Use"
 echo "      https://github.com/libhugetlbfs/libhugetlbfs.git for"
 echo "      hugetlb regression testing."
+
+echo "---------------------------"
+echo "running map_fixed_noreplace"
+echo "---------------------------"
+./map_fixed_noreplace
+if [ $? -ne 0 ]; then
+	echo "[FAIL]"
+	exitcode=1
+else
+	echo "[PASS]"
+fi
 
 echo "-------------------"
 echo "running userfaultfd"
@@ -178,6 +197,17 @@ else
 	echo "[PASS]"
 fi
 
+echo "-------------------------"
+echo "running mlock-random-test"
+echo "-------------------------"
+./mlock-random-test
+if [ $? -ne 0 ]; then
+	echo "[FAIL]"
+	exitcode=1
+else
+	echo "[PASS]"
+fi
+
 echo "--------------------"
 echo "running mlock2-tests"
 echo "--------------------"
@@ -189,6 +219,18 @@ else
 	echo "[PASS]"
 fi
 
+echo "-----------------"
+echo "running thuge-gen"
+echo "-----------------"
+./thuge-gen
+if [ $? -ne 0 ]; then
+	echo "[FAIL]"
+	exitcode=1
+else
+	echo "[PASS]"
+fi
+
+if [ $VADDR64 -ne 0 ]; then
 echo "-----------------------------"
 echo "running virtual_address_range"
 echo "-----------------------------"
@@ -210,6 +252,7 @@ if [ $? -ne 0 ]; then
 else
     echo "[PASS]"
 fi
+fi # VADDR64
 
 echo "------------------------------------"
 echo "running vmalloc stability smoke test"
diff --git a/user/linux-firmware/makefile b/user/linux-firmware/makefile
--- a/user/linux-firmware/makefile
+++ b/user/linux-firmware/makefile
@@ -1,29 +1,103 @@
-METHOD = git
-URL = git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
-VERSION = 9ee52be785cf91fc6a3c6aa27d484873f8270b72
+linux-firmware_METHOD = git
+linux-firmware_URL = git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
+linux-firmware_VERSION = 1eb2408c6feacccd10b02a49214745f15d1c6fb7
+linux-firmware_FINALTARGET = lndir
 
-linux-firmware_INSTALLVARS = :
-linux-firmware_ROMFS = linux-firmware_romfs
-SDIR = build/linux-firmware
+AUTOMAKE_ROMFS = linux-firmware_romfs
+SDIR = build/linux-firmware-install/lib/firmware
+
+###############################################################################
+# Candelatech Qualcomm firmwares
+###############################################################################
+CT_BASE_URL = https://www.candelatech.com/downloads
+FINALTARGET = ct_installed
+CT_PACKAGES =
+
+###############################################################################
+ifdef CONFIG_USER_LINUX_FIRMWARE_QCA9984_CT
+
+QCA9984_VERSION = 015
+QCA9984_FW_FILE = firmware-5-ct-full-community-12.bin-lede.$(QCA9984_VERSION)
+QCA9984_URL = $(CT_BASE_URL)/ath10k-9984-10-4b/$(QCA9984_FW_FILE)
+QCA9984_DOWNLOADHASH = c2f04da3285aad37baef9c37c9905a31927175dd234cd4378fd56c106e5c9379
+
+QCA9984_DST_DIR_NAME = hw1.0
+QCA9984_BOARD_BIN = board-2.bin
+
+CT_PACKAGES += QCA9984
+endif
+
+###############################################################################
+ifdef CONFIG_USER_LINUX_FIRMWARE_QCA988X_CT
+
+QCA988X_VERSION = 015
+QCA988X_FW_FILE = firmware-2-ct-full-community-22.bin.lede.$(QCA988X_VERSION)
+QCA988X_URL = $(CT_BASE_URL)/$(QCA988X_FW_FILE)
+QCA988X_DOWNLOADHASH = a3a760d0d72707feffa496b6d2266bd9195f09806553b36420b60c0f12b8b87e
+
+QCA988X_DST_DIR_NAME = hw2.0
+QCA988X_BOARD_BIN = board.bin
+
+CT_PACKAGES += QCA988X
+endif
+
+###############################################################################
+
+# linux-firmware has to be built first, as CT builds are depending on it
+AUTOMAKE_y = linux-firmware $(CT_PACKAGES)
 
 include $(ROOTDIR)/tools/automake.inc
 
+
+define ct_install_dep
+$(1)_METHOD = wget
+$(1)_DOWNLOADNAME = $($(1)_FW_FILE).$(1)
+.PHONY: build/$(1)-ct_installed
+build/$(1)-ct_installed: downloads/$($(1)_DOWNLOADNAME)
+	$(AT)echo "Verifying $$< using $($(1)_DOWNLOADHASH_METHOD) hash ..."
+	$(AT)HASH=`openssl dgst -$($(1)_DOWNLOADHASH_METHOD) $$< | cut -d' ' -f 2`; \
+	if [ "$$$$HASH" = "$($(1)_DOWNLOADHASH)" ]; then \
+		echo "Download file $$($(1)_DOWNLOADNAME) passed hash verification"; \
+	else \
+		echo "Download file $$($(1)_DOWNLOADNAME) failed hash verification"; \
+		echo "    Expected = $($(1)_DOWNLOADHASH)"; \
+		echo "    Got      = $$$$HASH"; \
+		exit 1; \
+	fi
+
+	$(AT)echo "Copying CT firmware $$< ..."
+	$(AT)rm -Rf build/$(1)-install
+	$(AT)mkdir -p build/$(1)-install/lib/firmware/ath10k/$(1)/$($(1)_DST_DIR_NAME)
+	$(AT)name=$($(1)_FW_FILE); cp $$< build/$(1)-install/lib/firmware/ath10k/$(1)/$($(1)_DST_DIR_NAME)/$$$${name%%-ct*}.bin
+	$(AT)cp build/linux-firmware-install/lib/firmware/ath10k/$(1)/$($(1)_DST_DIR_NAME)/$($(1)_BOARD_BIN) build/$(1)-install/lib/firmware/ath10k/$(1)/$($(1)_DST_DIR_NAME)/
+	$(AT)touch $$@
+endef
+$(foreach pkg,$(CT_PACKAGES),$(eval $(call ct_install_dep,$(pkg))))
+
 #
-# The entire set of linux-firmware is really big. So we only
-# install the firmwaree that we actually care about.
+# The entire set of Linux-firmware is really big. So we only
+# install the firmware that we actually care about.
 #
 linux-firmware_romfs:
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt2561.bin /lib/firmware/rt2561.bin
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt2661.bin /lib/firmware/rt2661.bin
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt2870.bin /lib/firmware/rt2870.bin
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt3071.bin /lib/firmware/rt3071.bin
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt3290.bin /lib/firmware/rt3290.bin
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt2561.bin /lib/firmware/rt2561s.bin
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt2860.bin /lib/firmware/rt2860.bin
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt3070.bin /lib/firmware/rt3070.bin
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt3090.bin /lib/firmware/rt3090.bin
-	$(ROMFSINST) -e CONFIG_R8169 -d $(SDIR)/rt73.bin /lib/firmware/rt73.bin
-	$(ROMFSINST) -e CONFIG_R8169 $(SDIR)/rtl_nic /lib/firmware/rtl_nic
-	$(ROMFSINST) -e CONFIG_ATH10K $(SDIR)/ath10k/QCA988X /lib/firmware/ath10k/QCA988X
-	$(ROMFSINST) -e CONFIG_ATH10K $(SDIR)/ath10k/QCA9984 /lib/firmware/ath10k/QCA9984
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT2561)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt2561.bin /lib/firmware/rt2561.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT2661)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt2661.bin /lib/firmware/rt2661.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT2870)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt2870.bin /lib/firmware/rt2870.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT3071)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt3071.bin /lib/firmware/rt3071.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT3290)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt3290.bin /lib/firmware/rt3290.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT2561S)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt2561.bin /lib/firmware/rt2561s.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT2860)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt2860.bin /lib/firmware/rt2860.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT3070)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt3070.bin /lib/firmware/rt3070.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT3090)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt3090.bin /lib/firmware/rt3090.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RT73)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/rt73.bin /lib/firmware/rt73.bin
+	$(ROMFSINST) -e CONFIG_R8169 -o '$(CONFIG_USER_LINUX_FIRMWARE_RTL_NIC)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' $(SDIR)/rtl_nic /lib/firmware/rtl_nic
 
+	@# Install only -ct or original firmwares for the ath10k chips
+	$(ROMFSINST) -e CONFIG_ATH10K -o '$(CONFIG_USER_LINUX_FIRMWARE_QCA988X)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -O '$(CONFIG_USER_LINUX_FIRMWARE_QCA988X_CT)' $(SDIR)/ath10k/QCA988X /lib/firmware/ath10k/QCA988X
+	$(ROMFSINST) -e CONFIG_ATH10K -o '$(CONFIG_USER_LINUX_FIRMWARE_QCA988X_CT)' build/QCA988X-install/lib/firmware/ath10k/QCA988X /lib/firmware/ath10k/QCA988X
+	$(ROMFSINST) -e CONFIG_ATH10K -o '$(CONFIG_USER_LINUX_FIRMWARE_QCA9984)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -O '$(CONFIG_USER_LINUX_FIRMWARE_QCA9984_CT)' $(SDIR)/ath10k/QCA9984 /lib/firmware/ath10k/QCA9984
+	$(ROMFSINST) -e CONFIG_ATH10K -o '$(CONFIG_USER_LINUX_FIRMWARE_QCA9984_CT)' build/QCA9984-install/lib/firmware/ath10k/QCA9984 /lib/firmware/ath10k/QCA9984
+	$(ROMFSINST) -e CONFIG_ATH10K -o '$(CONFIG_USER_LINUX_FIRMWARE_QCA6174)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' files/QCA6174 /lib/firmware/ath10k/QCA6174/hw3.0
+
+	$(ROMFSINST) -e CONFIG_IMX_SDMA -o '$(CONFIG_USER_LINUX_FIRMWARE_SDMA_IMX6Q)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' -d $(SDIR)/imx/sdma/sdma-imx6q.bin /lib/firmware/imx/sdma/sdma-imx6q.bin
+	$(ROMFSINST) -e CONFIG_MT76x2_COMMON -o '$(CONFIG_USER_LINUX_FIRMWARE_MT7662)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' $(SDIR)/mt7662.bin /lib/firmware/mt7662.bin
+	$(ROMFSINST) -e CONFIG_MT76x2_COMMON -o '$(CONFIG_USER_LINUX_FIRMWARE_MT7662_ROM_PATCH)$(CONFIG_USER_LINUX_FIRMWARE_ALL_FIRMWARE)' $(SDIR)/mt7662_rom_patch.bin /lib/firmware/mt7662_rom_patch.bin
diff --git a/vendors/Digi/AnywhereUSB8/digi_check_firmware_update b/vendors/Digi/AnywhereUSB8/digi_check_firmware_update
--- a/vendors/Digi/AnywhereUSB8/digi_check_firmware_update
+++ b/vendors/Digi/AnywhereUSB8/digi_check_firmware_update
@@ -43,10 +43,12 @@ umask 0022
 # PRODUCT_VERSION is a dotted quad version number, 0-255 for each number.
 # SUPPORTED_PRODUCT_IDS is a comma-separated list of hex numbers,
 #    leading 0x optional, case-insensitive.
+# OLDEST_SUPPORTED_VERSION is a dotted quad version, min fw update allowed
 export $(grep "^PRODUCT_VERSION=" ./version) >/dev/null
 export $(grep "^MIN_RUNNING_RELEASE=" ./version) >/dev/null
 export $(grep "^SUPPORTED_PRODUCT_IDS=" ./version | tr 'abcdefX' 'ABCDEFx') >/dev/null
 
+export $(grep "^OLDEST_SUPPORTED_VERSION=" /etc/version.info) >/dev/null
 export CURRENT_$(grep "^PRODUCT_VERSION=" /etc/version.info) >/dev/null
 NV_PRODUCT_ID=$(/bin/fw_printenv product_id | cut -d'=' -f2 | tr 'abcdefX' 'ABCDEFx')
 
@@ -79,6 +81,17 @@ echo "Current version: $CURRENT_PRODUCT_VERSION, New version: $PRODUCT_VERSION"
 cur_prod=$(parse_version "$CURRENT_PRODUCT_VERSION")
 new_prod=$(parse_version "$PRODUCT_VERSION")
 echo $cur_prod, $new_prod
+
+echo "OLDEST: $OLDEST_SUPPORTED_VERSION, NEW: $PRODUCT_VERSION"
+# Check PRODUCT_VERSION against minimum version
+if [ -n "$OLDEST_SUPPORTED_VERSION" ]; then
+	oldest_supported_version=$(parse_version "$OLDEST_SUPPORTED_VERSION")
+	echo "oldest: $oldest_supported_version"
+	if [ "$new_prod" -lt "$oldest_supported_version" ]; then
+		/usr/bin/logger -t fwupdate -p local5.err "![ERROR] Device cannot be downgraded to a version older than $OLDEST_SUPPORTED_VERSION.\n"
+		exit 1
+	fi
+fi
 
 # See if we have a min version for this update.
 if [ -n "$MIN_RUNNING_RELEASE" ]; then
diff --git a/vendors/Digi/TX64/rc b/vendors/Digi/TX64/rc
--- a/vendors/Digi/TX64/rc
+++ b/vendors/Digi/TX64/rc
@@ -1,7 +1,10 @@
-readonly LABEL_USERFS="UserFS"
-readonly GUID_USERFS="eceab4b2-cd57-49d9-b0b4-63b6808bfae9"
-readonly USERFS_PART=8
+readonly LABEL_OPTFS="UserFS"
+readonly GUID_OPTFS="eceab4b2-cd57-49d9-b0b4-63b6808bfae9"
+readonly OPTFS_PART=8
 readonly DRIVE=/dev/sda
+readonly CONFIGFS_FILE=/opt/.configfs
+# Leave ~500MB for OPT (in MB)
+readonly CONFIGFS_FILE_SIZE=4700
 
 hostname TX64
 
@@ -30,31 +33,41 @@ ip link set eth2 name eth3
 ip link set eth1 name eth2
 ip link set eth0 name eth1
 
-# init devices before we need any
-cp -ra /lib/udev/devices/. /dev
+# initialise devices before we need them
+/etc/rc.dev
 
 # /efi filesystem
-mount /dev/flash/efi /efi
+mount -o discard /dev/flash/efi /efi
 
-# Check if opt filesystem exists
-if ! sgdisk ${DRIVE} -p | grep -q "${LABEL_USERFS}"; then
+# load I2C driver with modified frequency (100kHz, because of the ATECC508)
+modprobe i2c-designware-core bus_speed=100
+modprobe i2c-designware-pci
+
+# instantiate ATECC508 device
+echo "atsha204-i2c 0x60" > /sys/bus/i2c/devices/i2c-1/new_device
+
+# Check if OPT filesystem exists
+if ! sgdisk ${DRIVE} -p | grep -q "${LABEL_OPTFS}"; then
 	echo "Creating new OPT filesystem..."
+
 	# Fix GPT
 	sgdisk ${DRIVE} -e
-	sgdisk ${DRIVE} -new 0::-0 --typecode=0:8300 --change-name=0:"${LABEL_USERFS}" --partition-guid=0:"${GUID_USERFS}" > /dev/null
+	sgdisk ${DRIVE} -new 0::-0 --typecode=0:8300 --change-name=0:"${LABEL_OPTFS}" --partition-guid=0:"${GUID_OPTFS}" > /dev/null
 	partprobe
-	mkfs.ext4 -F ${DRIVE}${USERFS_PART}
-	mount -t ext4 ${DRIVE}${USERFS_PART} /opt
-	mkdir /opt/config
+
+	mkfs.ext4 -F ${DRIVE}${OPTFS_PART}
+	mount -t ext4 -o discard ${DRIVE}${OPTFS_PART} /opt
+
 	ln -s /efi/grub /opt/boot
-	touch /opt/config/.init
+
 	umount /opt
 else
 	echo "Mounting OPT filesystem..."
 fi
 
+# Mount OPT
 fsck.ext4 -p /dev/flash/opt
-mount -t ext4 /dev/flash/opt /opt
+mount -t ext4 -o discard /dev/flash/opt /opt
 
 echo "Starting watchdog ..."
 watchdog /dev/watchdog
@@ -79,26 +92,28 @@ ifconfig lo 127.0.0.1
 #	exit 0
 #fi
 
+. /lib/configfs_lib.sh
+
+factory_reset=
+if nexcom-tool -f 2> /dev/null | grep -q 'set$'; then
+	# force erase if factory flag is set, this allows for it to be
+	# set while DAL is not actually running
+	factory_reset=1
+fi
+
 echo "Mounting config filesystem ..."
-if ! mount --bind /opt/config /etc/config
-then
-	echo "Cannot bind mount /etc/config to /opt/config..."
+if ! mount_configfs ${factory_reset} ; then
+	echo "Cannot mount config filesystem..."
 	echo "Using tmpfs for /etc/config."
 	mount -t tmpfs -o size=4M tmpfs /etc/config
 	touch /etc/config/.init
 fi
 [ "$(echo /etc/config/*)" = '/etc/config/*' ] && touch /etc/config/.init
 
-if nexcom-tool -f 2> /dev/null | grep -q 'set$'; then
-	# force erase if factory flag is set, this allows for it to be
-	# set while DAL is not actually running
-	touch /etc/config/.init
-fi
-
 if [ -f /etc/config/.init ]; then
 	echo "Factory defaulting config ..."
-	filter="($|/ssh_host_rsa_key|/ssh_host_dsa_key|/ssh_host_key|/id_rsa|/id_dsa|/identity|/accns.pem|/accns.crt|/unique.crt|/.init2)"
-	[ -f /etc/config/.init2 ] && filter='$'
+	filter="($|/ssh_host_rsa_key|/ssh_host_dsa_key|/ssh_host_key|/id_rsa|/id_dsa|/identity|/accns.pem|/accns.crt|/unique.crt|/.nocrypt|/.init2|/random-seed)"
+	[ -f /etc/config/.init2 ] && filter='($|/random-seed)'
 	touch /etc/config/.init2
 	find /etc/config -name '*' |
 		egrep -v "/etc/config$filter" |
@@ -114,19 +129,21 @@ fi
 
 cat /etc/inittab.d/* > /etc/inittab
 
-# speed up crypto
-#echo "Enabling parrallel crypto ..."
-#crconf add driver "pcrypt(authenc(hmac(sha1),cbc(aes)))" type 3 2> /dev/null
+# cryptography disabled mode
+if [ -e /etc/config/.nocrypt ] ; then
+	sh /etc/nocrypt
+	exit 0
+fi
 
 #load wifi module before we come up
 modprobe ath10k_pci
 
-# load I2C driver with modified frequency (100kHz, because of the ATECC508)
-modprobe i2c-designware-core bus_speed=100
-modprobe i2c-designware-pci
+# Note: it is safe to do this here, as the configfs-tool (used before) is
+# using the crypto chip to get the random number
+random_seed restore
 
-# instantiate ATECC508 device
-echo "atsha204-i2c 0x60" > /sys/bus/i2c/devices/i2c-1/new_device
+# init processing
+[ -x /etc/rcS ] && /etc/rcS
 
 # do the rc script processing
 actiond &
